<?php
/**
 * Plugin Name: TVA View Transcript button
 * Description: Adds a red "View transcript" button under the video on every Techspressionism WordPress page that shows a recording
 *              that has a transcript in the Techspressionism Video Archive (techspressionism.com/archive/). Matches by YouTube video ID.
 * Version: 1.0
 * Install: put this one file in wp-content/mu-plugins/ (a "must-use" plugin, active at once). Remove the file to remove the button.
 * The ID list below is written by scripts/make-wp-view-transcript.py from the archive's corpus; regenerate it when recordings are added.
 */
if (!defined('ABSPATH')) { exit; }

function tva_transcript_map() {
  return array(
    'JZFDck9gwH8' => 'interview-001-colin-goldberg',
    '2JTyaVoXMsQ' => 'interview-002-anne-spalter',
    'DJDMQvtiOQU' => 'interview-003-roz-dimon',
    'Hjej663DEjw' => 'interview-004-joseph-nechvatal',
    'qE6D2wrr1rU' => 'interview-005-davonte-bradley',
    'a5h-eBQYrks' => 'interview-006-patrick-lichty',
    'XLRoHnYg1dA' => 'interview-007-michael-pierre-price',
    '--L1ziEx3-A' => 'interview-008-steve-miller',
    'YaKIk32mYWw' => 'interview-009-andrea-bonaceto',
    'rO6UdqwFKFc' => 'interview-010-brandon-gellis',
    'nGPCwUZj9fs' => 'interview-011-michael-rees',
    'm6ca8UoF49M' => 'interview-012-gregory-little',
    'w6fW5oWbBdk' => 'interview-013-cee-moses',
    'DEIe5Z44tx0' => 'interview-014-carter-hodgkin',
    'aP2x9m5GMak' => 'interview-015-darcy-gerbarg',
    'sqMzJArwmhg' => 'interview-016-paul-d-miller-aka-dj-spooky-that-subliminal-kid',
    'k1kO0JSzqc8' => 'interview-017-tommy-mintz',
    'Jb-J_QTgufM' => 'interview-018-randi-matushevitz',
    'lXCEgu2Iz5k' => 'interview-019-malavika-mandal-andrew',
    'kfGb9OWyXEM' => 'interview-020-renata-janiszewska',
    'ywYWdI922tI' => 'interview-021-victor-acevedo',
    'FDFxHrpDvEI' => 'interview-022-karen-lafleur',
    'GReJ-zgJz-o' => 'interview-023-suzanne-anker',
    'RoCFEGxcw4Y' => 'interview-024-frank-gillette',
    '8x8eIkbpHws' => 'interview-025-verneda-lights',
    'iQL826mqyFg' => 'interview-026-nina-sobell',
    'Jj66toeEM0Q' => 'interview-027-cari-ann-shim-sham',
    'xkfYnuTP2zA' => 'interview-028-sasha-stiles',
    '4kHuGtuLoSY' => 'interview-029-claudia-hart',
    'Q-4Co29bgiM' => 'interview-030-carla-gannis',
    'z8fZvhQgl80' => 'presentation-001-digital-painting-and-drawing-1',
    'GvAkzINQBT8' => 'presentation-002-ai-as-creative-collaborator',
    'DtGglnJ4mdI' => 'presentation-003-collaborations-between-artists-and-scientists',
    '9u3WpSKe3bM' => 'presentation-004-digital-painting-and-drawing-2',
    'XgXtLT1I-T4' => 'presentation-005-moving-images-sequencing-as-visual-expression',
    'V3NO6tMIiPU' => 'presentation-006-digital-photography',
    'lW17XAepKs4' => 'presentation-007-how-technology-changes-artist-interactions-with',
    '1OgIwvY5_F4' => 'presentation-008-digital-sculpture-and-world-creation',
    '8aQDDA-u0io' => 'presentation-009-technology-and-art-with-colin-goldberg',
    '-8Glurhxyms' => 'roundtable-001-curators-in-conversation',
    'S_q30BIvh8c' => 'roundtable-002-approach',
    '_oxmBXSdyNk' => 'roundtable-003-science-and-art-part-one',
    '4HfJCnIp8XE' => 'roundtable-004-science-and-art-part-two',
    'BphNOUbReFs' => 'roundtable-005-four-techspressionist-artists',
    'lVI5UE-AD9E' => 'roundtable-006-founders-five-years-later',
    'lxunnn1tM5M' => 'salon-008-pons-sun-andrew-pointer-boyd-wilson-lafleur',
    'wyAHD-HTAfM' => 'salon-009-dimon-kralikova-lichty-kell-moses',
    '2stJTcEAhGY' => 'salon-010-spalter-gerbarg-karver-gellis-bradley',
    'e5dH26wP9gk' => 'salon-011-miller-henderson-woods-swinburne-kralikova',
    'colPPMiP6gk' => 'salon-012-carter-hodgkin-michael-rees-colin-goldberg-michael',
    'b4hmMbnUuKE' => 'salon-013-negin-ehtesabian-diane-marsella-sue-beyer',
    'MZ7JzodmmIA' => 'salon-014-susan-de-troy-sherry-karver-deann-stein-hasinoff',
    'rwlq9lFhe18' => 'salon-015-andrea-bonaceto-tommy-mintz-clive-holden',
    'syXkJWTwCJc' => 'salon-016-randi-matushevitz-gary-hopkins-roz-dimon',
    'UE3rbE3XMf0' => 'salon-017-michael-pierre-price-greggory-hill-michael-pointer',
    'wvwrqw0MRfI' => 'salon-018-paul-d-miller-aka-dj-spooky-that-subliminal-kid-and-ap',
    'mA3da8lu0iU' => 'salon-019-gregory-little-and-lee-musgrave',
    'Hhm4t38sjUA' => 'salon-020-victor-acevedo-and-christine-sciulli',
    'CtSAsaLkmtQ' => 'salon-021-cynthia-beth-rubin-and-renata-janiszewska',
    'sbMbH55efqM' => 'salon-022-lorin-roser-and-nina-kuo-and-emma-anne-johnson',
    'pmau5CDJUiQ' => 'salon-023-rebecca-tombaugh-and-cynthia-didonato',
    'fEWi09zryY0' => 'salon-024-malavika-mandal-andrew-and-lee-schnaiberg',
    'BbLPmZfJVOs' => 'salon-025-lights-gerbarg-stein-hasinoff-bradley-tintin23x',
    'cYU7eKBcCto' => 'salon-026-collab-2-exhibition-opening-reception',
    'QrGxzCL_ScA' => 'salon-027-davonte-davo-bradley-and-holly-gordon',
    'fFUTukSn4gw' => 'salon-028-tommy-mintz-and-stephanie-sydney',
    'ADjcjvSQViE' => 'salon-029-techspressionism-2021-opening',
    't0JhtlP3olQ' => 'salon-030-sahar-moussavi-and-skywaterr',
    '7dDowJIxuJw' => 'salon-031-cee-moses-niftorian-and-dubwoman',
    'CbqAI1PKEkY' => 'salon-032-roz-dimon-lovid-moritz-albrecht-colin-goldberg',
    'dJbRASddqhg' => 'salon-033-david-bloom-lindsay-kokoska-nina-sobell',
    'lUmGsX0p78E' => 'salon-034-old-school-open-mic-with-robert-dugrenier',
    'b8yrqPIj934' => 'salon-035-lily-kostrzewa-prince-magnolia-x-st-rivera-michael',
    'l52RGfTiatE' => 'salon-036-seungjin-lee-and-dalton-portella',
    '1hehNivSYTo' => 'salon-037-diana-de-avila-and-patrick-lichty',
    'ufGrnsSaMQo' => 'salon-038-steve-miller-and-lee-day',
    '2KEDFrtlQTY' => 'salon-039-old-school-open-mic-obsolescence',
    'Z-RFTbQ7GF8' => 'salon-040-collage-show-and-tell',
    'XUBL7L41hjA' => 'salon-041-climate-show-and-tell',
    'QcotNCjBuIQ' => 'salon-042-techspressionism-digital-and-beyond-international',
    'KyBLFghq4N0' => 'salon-043-femme-tech',
    'PecHOYGSnWY' => 'salon-044-east-end-tech',
    'pxavr84wDJs' => 'salon-045-and-beyond-show-and-tell',
    'xo2ql3MgJlw' => 'salon-046-weird-media',
    'ggbxdDYOEz4' => 'salon-047-materiality',
    'WCOXAr5_wdE' => 'salon-048-adaptation',
    'iVP63DGbCGY' => 'salon-049-movement',
    'zj79kXJHdFU' => 'salon-050-output-and-fabrication',
    'xTm1wXYzdCI' => 'salon-051-ai-engines-friend-or-foe',
    'LuFuRGhgnmQ' => 'salon-052-art-and-physics',
    'ACwcZ2XHb9E' => 'salon-053-photography-and-media-confluence',
    'NFt4AfP-aRA' => 'salon-054-open-studios',
    'sfMxOAC97Yo' => 'salon-055-the-nft-space',
    'I7-nXjL2koA' => 'salon-056-cultural-influences',
    'Q_5yvTBIL5M' => 'salon-057-nightmares',
    '7zhZis1d3po' => 'salon-058-dreams',
    'M3lz4NxC8N4' => 'salon-059-ai-trends-and-issues',
    'Iu25Pv7EqK0' => 'salon-060-media-platforms',
    'axa3_RqLoWw' => 'salon-061-open-studios',
    'k8Prps3LUKE' => 'salon-062-art-pirates',
    'j-nNutQp8wc' => 'salon-063-breaking-borders',
    'hyYpGwwt2G0' => 'salon-064-layers',
    'qBc4IjFobIg' => 'salon-065-revolution',
    'UBx4LDG--60' => 'salon-066-mediums',
    '-m_aiHkazGI' => 'salon-067-untitled',
    'vMQWnv70FvA' => 'salon-068-appropriation',
    '90wRPqAgA98' => 'salon-069-monochrome',
    'GW0Vig0R8wA' => 'salon-070-learning-through-making',
    'rYpn_GAV3I4' => 'salon-071-growth',
    'zsJAhBFVn5s' => 'salon-072-environment',
    'oimOOlyY0BY' => 'salon-073-counterpoint',
    'IzL0mVtw8do' => 'salon-074-taking-stock-open-mic',
    'UwkMNkLGZ6Q' => 'salon-075-falling-leaves',
    'ni_Sr6-zBXg' => 'salon-076-phreaking',
    'e58ctMQ-ccc' => 'salon-077-december-7-2023',
    'fEzz3PiADrU' => 'salon-078-january-4-2024',
    'AXCiQqjVHyA' => 'salon-079-photography',
    'EoF3pT-iZSg' => 'salon-080-march-7-2024',
    'VfiH4ayJbGE' => 'salon-081-april-4-2024',
    'Lc0jSsfTb9A' => 'salon-082-april-4-2024',
    'ekZHtu7TM9Q' => 'salon-083-influences',
    '9uB83V9qp8M' => 'salon-084-independence',
    'OdbOncqxQ7s' => 'salon-085-perspective',
    'vE2cOCt7b0o' => 'salon-086-hello-brooklyn',
    'RFWaEX_2QPk' => 'salon-087-wild-and-newfangled-techspressionism',
    'htDS7UsZjyA' => 'salon-088-education',
    'gesSwVo36wo' => 'salon-089-mariniana',
    'o7pyuyo35iU' => 'salon-090-origins-part-one',
    '5RXM-lkRkhI' => 'salon-091-origins-part-two',
    'bdzAVjhHPaw' => 'salon-092-breaking-ai',
    'PrrvyUZvD5k' => 'salon-093-live-from-cape-cod',
    'npycONiSa_c' => 'salon-094-150-media-stream-chicago',
    'LntR7Bo5jmA' => 'salon-095-live-from-chelsea',
    'VaKW4Gnh9eE' => 'salon-096-open-studios',
    'w6dn7xxG6ds' => 'salon-097-creative-coding',
    '3JOMa_JYp9s' => 'salon-098',
    '1cuvfkJw3rs' => 'salon-099-floating-questions',
    'XpQRmDG0f5s' => 'salon-100-hello-uzbekistan',
    'l9TiCHiOgpQ' => 'salon-101-open-mic',
    'VxS9DBtseCE' => 'salon-102-art-science-intra-action',
    'QT6X7WrTTmA' => 'salon-103-generative-ai',
    '7zk9GzgaLvs' => 'salon-104-history-theory-connectivity',
    'P-sfs-tCkgw' => 'salon-105-every-woman-biennial',
    'kAXUgOIUjw0' => 'salon-106-france',
    'xm747MwGbiA' => 'salon-107-new-artists',
    'RSGBYaBbWgg' => 'salon-108-los-angeles-and-beyond',
    'w8IHfgE2veI' => 'salon-109-open-mic-august-2026',
    'pMRthFj7aw4' => 'salon-110-loop-art-critique',
  );
}

function tva_view_transcript_button($content) {
  if (is_admin() || !is_singular() || !in_the_loop() || !is_main_query()) { return $content; }
  if (strpos($content, 'tva-view-transcript') !== false) { return $content; }
  if (!preg_match('~youtube(?:-nocookie)?\.com/(?:embed/|watch\?v=)([A-Za-z0-9_-]{11})~', $content, $m)) { return $content; }
  $map = tva_transcript_map();
  if (!isset($map[$m[1]])) { return $content; }
  $url = 'https://techspressionism.com/archive/' . $map[$m[1]] . '/';
  $button = '<p class="tva-view-transcript" style="text-align:center;margin:1.2em 0;"><a href="' . esc_url($url) . '" '
          . 'style="display:inline-block;background:#FF0000;color:#fff;font-weight:700;padding:.8em 2em;text-decoration:none;border-radius:2px;">View transcript</a></p>';
  // right under the video block; if the page is built differently, at the top of the content
  $n = 0;
  $out = preg_replace('~(<div class="wpb_video_wrapper">.*?</iframe>(?:\s*</div>){4})~s', '$1' . $button, $content, 1, $n);
  return $n ? $out : $button . $content;
}
add_filter('the_content', 'tva_view_transcript_button', 30);
